language: go
sudo: required

go:
- "1.15"
- master

matrix:
    allow_failures:
        - go: master
    fast_finish: true

before_install:
- sudo apt-get update -qq
- sudo apt-get install automake libtool make gcc pkg-config
- make yara

install:
- cd -

script:
- env GO111MODULE=on make

deploy:
    provider: releases
    api_key:
        secure: sL57IJ9NXBcOMel9+wgswtT5qqMOyCqCCVIShuU/KfV+P4mD4L+R6vf1cNS1fZ56Sgp51DXkyTWMgEFMjBZtJh7WaGe52bbRCXBnwUAXZ6h2vASZGVnqEqf18Qhl76pJc1eaZHcZNuYId2Ff99SH61VjAKCoSY0nXukSSdzjHp5lYpZu44bJf7OhpUcGL6NkjKybRm6F+qLqZ4lQQ1HCx3HEXZ57b1NX7anyZ4RLUBUY17sIoM+COYKC3QyjcffBBLI9L1VjtkyQ0pXk+SBpieC+Nx9t0NzkQrmG6CyDCUGkOhll4/I3ivypj8iejHNCTRSNMjvwj2A089Q/drT2xCdr3I+E0J+fMX2R5cQWM/EDym65S2pi0Lt2N8KOvY16iZ8drCVrOBBb/9cNto7cwXxURQ8em3QazxvXSJG7I65O0tDx6EuQNGcrZ+Y658f+l/MIPF2YukNa8TT9YbW4h3BdywQ0VU8HIFeqWIwwAPu+cCtU3x2jVdpLAp+xL9x6OM3ev4mELv2DiJ+6lP3yg3dxdr1+FrE2ATiUGnc7R/W4X+PgPI6WVClRhXSUx78aKeWvqIwcjkyAKFgWYOZdT24YAYrp6egU5CX5Hk8+zmxG+TgvXTn7T22x3UHInjh7T3QmBMbvyEiHYC/naqTCSPixWGnqYfq3kJqouQ0DGQ8=
    file: build/phishdetect-node
    skip_cleanup: true
    on:
        tags: true
        repo: phishdetect/phishdetect-node
