name: Build and release

on: 
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update && sudo apt-get install wget
    - name: Downloading Yara
      run: |
        wget https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.2.tar.gz
        tar -zxvf v4.1.2.tar.gz
    - name: Install yara dependencies
      working-directory: ./yara-4.1.2
      run : |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          gcc-multilib \
          libtool \
          libjansson-dev \
          libmagic-dev \
          libssl-dev  \
          protobuf-compiler \
          protobuf-c-compiler \
          libprotobuf-c-dev
    - name: Configure Yara
      working-directory: ./yara-4.1.2
      run: |
        ./boostrap.sh
        ./configure
    - name: Compile Yara
      working-directory: ./yara-4.1.2
      run: make && sudo make install
    - uses: actions/checkout@v2
    - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH
    - name: Build Linux binary
      run: make
    - name: Upload Linux binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/phishdetect-node
        asset_name: phishdetect-node_linux_amd64
        tag: ${{ github.ref }}
        overwrite: true
